### ISSUE TITLE
Duplicate `cbor.dumps()` in sign.py

### ISSUE THREAD

**Issue by bergzand** [ARMmbed/suit-manifest-generator#13]
Hi,

It looks to me that there is a duplicate `cbor.dumps()` in the sign.py code:

https://github.com/ARMmbed/suit-manifest-generator/blob/89a8778ade3c99b7cee77ed0a8b422e3e065bf24/suit_tool/sign.py#L88-L95

The current code creates a signature from a cbor bstr wrapped version of the `Sig_structure`. I think (if I remember the COSE spec) the signature should be based on the plain cbor representation of the `Sig_structure`

**Comment by bremoran** [comment]
cc @maciejbocianski
