### ISSUE TITLE
Python UUIDs not RFC4122 compliant

### ISSUE THREAD

**Issue by bremoran** [ARMmbed/suit-manifest-generator#15]
There is a byte ordering problem in the Python UUID library.

**Comment by bergzand** [comment]
Do you have an example of this? I'm curious because our internal UUID library seems to match the results from the Python library :)

**Comment by bremoran** [comment]
I tried to confirm, but I was unable to find any evidence to support this issue. Further testing may be needed for NCS and Microsoft UUIDs, but the UUIDs defined in RFC4122 do not appear to have an ordering problem.
