### ISSUE TITLE
Signatures computed with suit-tool do not match those in I-D version 04

### ISSUE THREAD

**Issue by lindemer** [ARMmbed/suit-manifest-generator#16]
I'm trying to parse the examples found in the [latest SUIT manifest I-D](https://tools.ietf.org/html/draft-ietf-suit-manifest-04), but I haven't been able to verify any of the signatures with the public key provided. 

As a sanity check, I copied a few of the unsigned manifests from the I-D and ran `suit-tool -l debug sign` with the provided private key. The manifest hashes computed by `suit-tool` match those in the I-D, but the authentication wrapper signatures are different. I _also_ couldn't verify the these signatures with the corresponding public key. (I did double check that the public and private keys match.)

It seems that either the Sig_structure is being serialized incorrectly, or the keys in the I-D are incorrect, or both. Has the output of `suit-tool sign` been verified with any other COSE libraries?

**Comment by lindemer** [comment]
In addition to the above, the manifest digests produced by `suit-tool` match the examples in the I-D, but I have not been able to replicate these, either. I've tried two different SHA256 implementations, with both the raw manifest and the manifest wrapped with a CBOR byte string header. Perhaps the I-D is underspecified with regards to how this hash should be generated.

**Comment by bergzand** [comment]
@motet This sounds awfully similar to #13. I had the same issue that signed suit manifest could not be properly verified. I think this is a bug in the COSE sign code due to a duplicate `cbor.dumps()`

**Comment by lindemer** [comment]
Thanks @bergzand, that must be the issue. I figured out the issue with the message digests. The hex-represented manifests in the I-D's example section start with a map header. That has to be removed before computing the digest. (Closing this now because it's a duplicate.)
