### ISSUE TITLE
source-component value varies between generator calls

### ISSUE THREAD

**Issue by mpzaborski** [ARMmbed/suit-manifest-generator#24]
Observed on: master (3d87195).
In example3 (Load from External Storage) `source-component` in load sometimes equals 0, sometimes 1:
[12, 0, 19, {**22: 1**}, 22, null, 3, null]
or:
[12, 0, 19, {**22: 0**}, 22, null, 3, null]

I tracked it down, and something undetermined happens in manifest.py line 327 `return suitCommonInfo.component_id_to_index(self)`: 

When I debug I observe randomly:
`self.component_ids[0].items[0].v == b'\x01'`
or
`self.component_ids[0].items[0].v == b'\x00' `
 
I don't see any pattern there.

The issue occurs not only in source-component, but also with other items that use `component_id_to_index` function

**Comment by mpzaborski** [comment]
I think I found the culprit:
In manifest.py line 351 (master 3d87195) ‘suitCommonInfo.component_ids = self.items’ 

self.items are not sorted, and because of that they appear in suitCommonInfo.component_ids in random order.

**Comment by mpzaborski** [comment]
Please see https://github.com/ARMmbed/suit-manifest-generator/pull/27 for example solution.

**Comment by bremoran** [comment]
@mpzaborski, Please could you verify that #28 fixes this issue?

**Comment by mpzaborski** [comment]
Fix implemented in #28 works

**Comment by mpzaborski** [comment]
Fix implemented in #28 works
